services:
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      # root user is `root`
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_mysql_db

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: test_postgres_db
    ports:
      - "5432:5432"
